export type ReservationChannelIdentity = {
  source?: string | null;
  externalProvider?: string | null;
};

const EMPTY_LABEL = "—";
const EXTERNAL_CHANNEL_LABEL = "External Channel";

const VISIBLE_CHANNEL_LABELS: Readonly<Record<string, string>> = Object.freeze({
  CHANNEX: "Pin&Go Connect",
  PIN_GO_CONNECT: "Pin&Go Connect",

  PIN_GO_DIRECT: "Pin&Go Direct",
  DIRECT_BOOKING: "Pin&Go Direct",

  PIN_GO_MANUAL: "Pin&Go Manual",
  MANUAL: "Pin&Go Manual",

  PIN_GO: "Pin&Go",

  AIRBNB: "Airbnb",
  AIR_BNB: "Airbnb",
  VRBO: "Vrbo",
  BOOKING_COM: "Booking.com",
  BOOKINGCOM: "Booking.com",

  GUESTY: "Guesty",
  CLOUDBEDS: "Cloudbeds",
  HOSTAWAY: "Hostaway",
  LODGIFY: "Lodgify",
});

function cleanValue(value?: string | null) {
  return String(value ?? "").trim();
}

function normalizeLookupKey(value: string) {
  return value
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

function formatUnknownVisibleChannel(rawValue: string) {
  if (!rawValue) return EMPTY_LABEL;

  if (/[a-z]/.test(rawValue)) {
    return rawValue;
  }

  if (/^[A-Z0-9]+$/.test(rawValue)) {
    return rawValue.charAt(0) + rawValue.slice(1).toLowerCase();
  }

  return EXTERNAL_CHANNEL_LABEL;
}

/**
 * Converts an internal reservation channel/provider token into host-facing copy.
 * Internal database/API values remain unchanged.
 */
export function getVisibleChannelLabel(value?: string | null) {
  const rawValue = cleanValue(value);

  if (!rawValue) return EMPTY_LABEL;

  const lookupKey = normalizeLookupKey(rawValue);
  const knownLabel = VISIBLE_CHANNEL_LABELS[lookupKey];

  return knownLabel ?? formatUnknownVisibleChannel(rawValue);
}

/**
 * Reservation Source describes where the booking originated.
 * Prefer source (for example Airbnb) and only fall back to the provider when
 * the source is unavailable.
 */
export function getVisibleReservationSourceLabel(
  identity: ReservationChannelIdentity
) {
  const source = cleanValue(identity.source);

  if (source) {
    return getVisibleChannelLabel(source);
  }

  return getVisibleReservationProviderLabel(identity.externalProvider);
}

/**
 * Reservation Provider describes the integration used to ingest/manage the
 * reservation. CHANNEX is intentionally presented as Pin&Go Connect.
 */
export function getVisibleReservationProviderLabel(
  externalProvider?: string | null
) {
  return getVisibleChannelLabel(externalProvider);
}

/**
 * Sanitizes host-facing operational text without changing stored audit data.
 * This is intended for summaries/errors that may contain internal provider
 * names generated by backend contracts.
 */
export function sanitizeWhiteLabelText(value?: string | null) {
  const text = cleanValue(value);

  if (!text) return text;

  return text
    .replace(/PIN_GO_DIRECT/gi, "Pin&Go Direct")
    .replace(/PIN_GO_MANUAL/gi, "Pin&Go Manual")
    .replace(/DIRECT_BOOKING/gi, "Pin&Go Direct")
    .replace(/CHANNEX/gi, "Pin&Go Connect");
}
