export type PublicListingDetails = {
  version: number;
  accommodationType: "ENTIRE_PLACE"|"PRIVATE_ROOM"|"SHARED_ROOM"|null;
  bedroomCount: number|null;
  fullBathroomCount: number|null;
  halfBathroomCount: number|null;
  minimumPrimaryBookingGuestAge: number|null;
  childrenPolicy: "ALLOWED"|"NOT_ALLOWED"|"UNKNOWN";
  infantsPolicy: "ALLOWED"|"NOT_ALLOWED"|"UNKNOWN";
  adultsOnly: "YES"|"NO"|"UNKNOWN";
  petsPolicy: "ALLOWED"|"NOT_ALLOWED"|"UNKNOWN";
  smokingPolicy: "ALLOWED"|"NOT_ALLOWED"|"UNKNOWN";
  vapingPolicy: "ALLOWED"|"NOT_ALLOWED"|"UNKNOWN";
  eventsPolicy: "ALLOWED"|"NOT_ALLOWED"|"UNKNOWN";
  unregisteredVisitorsPolicy: "ALLOWED"|"NOT_ALLOWED"|"UNKNOWN";
  quietHoursEnabled: "YES"|"NO"|"UNKNOWN";
  quietHoursStart: string|null;
  quietHoursEnd: string|null;
  parkingAvailability: "YES"|"NO"|"UNKNOWN";
  parkingType: "PRIVATE"|"GARAGE"|"DRIVEWAY"|"STREET"|"LOT"|"OTHER"|null;
  parkingFeeType: "FREE"|"PAID"|"UNKNOWN"|null;
  parkingVehicleCapacity: number|null;
  smokeDetector: "YES"|"NO"|"UNKNOWN";
  carbonMonoxideDetector: "YES"|"NO"|"UNKNOWN";
  exteriorSecurityCameras: "YES"|"NO"|"UNKNOWN";
  exteriorSecurityCamerasDisclosureEn: string|null;
  exteriorSecurityCamerasDisclosureEs: string|null;
  animalsOnProperty: "YES"|"NO"|"UNKNOWN";
  animalsOnPropertyDisclosureEn: string|null;
  animalsOnPropertyDisclosureEs: string|null;
  stepFreeEntrance: "YES"|"NO"|"UNKNOWN";
  entranceStepCount: number|null;
  elevatorAvailable: "YES"|"NO"|"UNKNOWN";
  accessibleParking: "YES"|"NO"|"UNKNOWN";
  stepFreeBedroomAccess: "YES"|"NO"|"UNKNOWN";
  stepFreeBathroomAccess: "YES"|"NO"|"UNKNOWN";
  stepFreeShower: "YES"|"NO"|"UNKNOWN";
  sleepingAreas: Array<{
    kind:"BEDROOM"|"SLEEPING_AREA"; nameEn:string|null; nameEs:string|null; sortOrder:number;
    beds:Array<{type:"KING"|"QUEEN"|"DOUBLE"|"SINGLE"|"BUNK"|"SOFA_BED"|"FUTON"|"CRIB"|"OTHER";quantity:number}>;
  }>;
  sharedSpaces:Array<{type:string;labelEn:string|null;labelEs:string|null;sortOrder:number}>;
  safetyConsiderations:Array<{type:string;descriptionEn:string|null;descriptionEs:string|null;sortOrder:number}>;
  additionalConsiderations:Array<{titleEn:string|null;titleEs:string|null;descriptionEn:string|null;descriptionEs:string|null;sortOrder:number}>;
};
