import type { PublicListingDetails } from "./publicListingDetails.types";
import { beforeBookingFacts, listingFactLabels, publicBathrooms, totalPublicBeds } from "./publicListingDetails.logic.js";

export { beforeBookingFacts, listingFactLabels, publicBathrooms, totalPublicBeds } from "./publicListingDetails.logic.js";
const bedName={KING:{en:"king bed",es:"cama king"},QUEEN:{en:"queen bed",es:"cama queen"},DOUBLE:{en:"double bed",es:"cama doble"},SINGLE:{en:"single bed",es:"cama individual"},BUNK:{en:"bunk bed",es:"litera"},SOFA_BED:{en:"sofa bed",es:"sofá cama"},FUTON:{en:"futon",es:"futón"},CRIB:{en:"crib",es:"cuna"},OTHER:{en:"bed",es:"cama"}} as const;

type Lang="en"|"es";
function bedText(b:PublicListingDetails["sleepingAreas"][number]["beds"][number],l:Lang){return `${b.quantity} ${bedName[b.type][l]}`;}
export function PublicListingDetailsSections({details,language}:{details?:PublicListingDetails|null;language:Lang}){
 if(!details)return null; const sleep=details.sleepingAreas.filter(a=>a.beds.length); const facts=beforeBookingFacts(details,language);
 const disclosures=[
  details.exteriorSecurityCameras==="YES"?(language==="es"?details.exteriorSecurityCamerasDisclosureEs||details.exteriorSecurityCamerasDisclosureEn:details.exteriorSecurityCamerasDisclosureEn||details.exteriorSecurityCamerasDisclosureEs):null,
  details.animalsOnProperty==="YES"?(language==="es"?details.animalsOnPropertyDisclosureEs||details.animalsOnPropertyDisclosureEn:details.animalsOnPropertyDisclosureEn||details.animalsOnPropertyDisclosureEs):null,
  ...details.safetyConsiderations.map(x=>language==="es"?x.descriptionEs||x.descriptionEn:x.descriptionEn||x.descriptionEs),
 ].filter((x):x is string=>Boolean(x));
 return <>{sleep.length?<section className="pbe-section pbe-listing-details" aria-labelledby="pbe-sleep-title"><div className="pbe-section-heading"><p className="pbe-kicker">{language==="es"?"DISTRIBUCIÓN":"SLEEPING ARRANGEMENTS"}</p><h2 id="pbe-sleep-title">{language==="es"?"Dónde dormirás":"Where you'll sleep"}</h2></div><div className="pbe-listing-card-grid">{sleep.map((a,i)=><article className="pbe-listing-card" key={`${a.kind}-${a.sortOrder}-${i}`}><span aria-hidden="true">🛏</span><h3>{(language==="es"?a.nameEs||a.nameEn:a.nameEn||a.nameEs)||(a.kind==="BEDROOM"?(language==="es"?`Dormitorio ${i+1}`:`Bedroom ${i+1}`):(language==="es"?"Área para dormir":"Sleeping area"))}</h3><p>{a.beds.map(b=>bedText(b,language)).join(" · ")}</p></article>)}</div></section>:null}
 {(facts.length||details.sharedSpaces.length||disclosures.length||details.additionalConsiderations.length)?<section className="pbe-section pbe-listing-details" aria-labelledby="pbe-know-title"><div className="pbe-section-heading"><p className="pbe-kicker">{language==="es"?"ANTES DE RESERVAR":"BEFORE YOU BOOK"}</p><h2 id="pbe-know-title">{language==="es"?"Lo que debes saber":"Things to know"}</h2></div><div className="pbe-listing-know-grid">{facts.length?<div><h3>{language==="es"?"Requisitos y reglas":"Requirements & rules"}</h3><ul>{facts.map((x,i)=><li key={i}>{x}</li>)}</ul></div>:null}{details.sharedSpaces.length?<div><h3>{language==="es"?"Espacios compartidos":"Shared spaces"}</h3><ul>{details.sharedSpaces.map((x,i)=><li key={i}>{(language==="es"?x.labelEs||x.labelEn:x.labelEn||x.labelEs)||x.type.replaceAll("_"," ")}</li>)}</ul></div>:null}{disclosures.length?<div><h3>{language==="es"?"Seguridad":"Safety"}</h3><ul>{disclosures.map((x,i)=><li key={i}>{x}</li>)}</ul></div>:null}{details.additionalConsiderations.length?<div><h3>{language==="es"?"Detalles importantes":"Additional details"}</h3><ul>{details.additionalConsiderations.map((x,i)=><li key={i}><strong>{language==="es"?x.titleEs||x.titleEn:x.titleEn||x.titleEs}</strong>{(language==="es"?x.descriptionEs||x.descriptionEn:x.descriptionEn||x.descriptionEs)?` — ${language==="es"?x.descriptionEs||x.descriptionEn:x.descriptionEn||x.descriptionEs}`:""}</li>)}</ul></div>:null}</div></section>:null}</>;
}
